---
- name: Conditionally install packages
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    packages_to_check:
      - git
      - java
      - python3

  tasks:

    - name: Check if package is installed
      shell: "rpm -q {{ item }}"
      register: pkg_status
      ignore_errors: yes
      loop: "{{ packages_to_check }}"

    - name: Install missing packages
      yum:
        name: "{{ item.item }}"
        state: present
      when: item.rc != 0
      loop: "{{ pkg_status.results }}"
      loop_control:
        label: "{{ item.item }}"