---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:

     - name: Install Git on Host Machines
       action: yum pkg=git state=present

     - name: Install docker on Host Machines
       action: yum pkg=docker state=present
       
